---
sidebar: sidebar
permalink: whats-new.html
keywords: what's new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes
summary: Learn what's new with Azure NetApp Files support in BlueXP.
---

= What's new
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Learn what's new with Azure NetApp Files in BlueXP.

//tag::whats-new[]
== 22 April 2024

=== Volume templates no longer supported

You can no longer create a volume from a template. This action was associated with the BlueXP remediation service, which is no longer available.

== 11 April 2021

=== Support for volume templates

A new Application Templates service enables you to set up a volume template for Azure NetApp Files. The template should make your job easier because certain volume parameters will already be defined in the template, such as capacity pool, size, protocol, VNet and subnet where the volume should reside, and more. When a parameter is already predefined, you can just skip to the next volume parameter.

* https://docs.netapp.com/us-en/bluexp-remediation/concept-resource-templates.html[Learn about Application Templates and how you can use them in your environment^]
* https://docs.netapp.com/us-en/bluexp-azure-netapp-files/task-create-volumes.html[Learn how to create an Azure NetApp Files volume from a template]

== 8 March 2021

=== Dynamically change service levels

You can now dynamically change the service level for a volume to meet workload needs and optimize your costs. The volume is moved to the other capacity pool with no impact to the volume.

https://docs.netapp.com/us-en/bluexp-azure-netapp-files/task-manage-volumes.html#change-the-volumes-service-level[Learn how to change a volume's service level].

//end::whats-new[]

== 3 August 2020

=== Azure NetApp Files set up and management

Set up and manage Azure NetApp Files directly from Cloud Manager. After you create an Azure NetApp Files working environment, you can complete the following tasks:

* Create NFS and SMB volumes.

* Manage capacity pools and volume snapshots
+
Cloud Manager enables you to create, delete, and restore volume snapshots. You can also create new capacity pools and specify their service levels.

* Edit a volume by changing its size and managing tags.

The ability to create and manage Azure NetApp Files directly from Cloud Manager replaces the previous data migration functionality.

== 5 April 2020

=== Data migration to Azure NetApp Files

You can now migrate NFS or SMB data to Azure NetApp Files directly from Cloud Manager. Data syncs are powered by BlueXP copy and sync.
