---
sidebar: sidebar
permalink: whats-new.html
keywords: what's new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes
summary: Learn what's new with Azure NetApp Files support in Cloud Manager.
---

= What's new
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Learn what's new with Azure NetApp Files support in Cloud Manager.

tag::whats-new[]
== 03 Aug 2020

=== Azure NetApp Files set up and management

You can now set up and manage Azure NetApp Files directly from Cloud Manager. After you create an Azure NetApp Files working environment, you can complete the following tasks:

* Create NFS and SMB volumes.

* Manage capacity pools and volume snapshots
+
Cloud Manager enables you to create, delete, and restore volume snapshots. You can also create new capacity pools and specify their service levels.

* Edit a volume by changing its size and managing tags.

== 05 Apr 2020

=== Data migration to Azure NetApp Files

You can now migrate NFS or SMB data to Azure NetApp Files directly from Cloud Manager. Data syncs are powered by NetApp's Cloud Sync service.
end::whats-new[]
